### ISSUE TITLE
false-identification of f-string

### ISSUE THREAD

**Issue by bhakta0007** [mdebi/fstring-converter#2]
This is a valid format:

"{X}:{Y}".format(X=1, Y=2)

the extension sticks in an f' for this string. This should be corrected as well

**Comment by mdebi** [comment]
Hi again. I never intended to support `.format` style of code with this tool. The `.format` can be written using an f-string. All the syntax variations can be challenging to handle in extension side and not sure with f-string if that is used much with newer codes.

https://github.com/asottile/pyupgrade helps converting `.format` style to f-string if those are in large scale.

If there is more interest with supporting `.format` style in future, I can look into that. Since personally I am using f-strings always, I am not planning to look at it currently.
